run:
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - bodyclose
    - containedctx
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - godot
    - goimports
    - goprintffuncname
    - gosec
    - ireturn
    - makezero
    - mirror
    - nakedret
    - nestif
    - noctx
    - nosprintfhostport
    - paralleltest
    - prealloc
    - revive
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - wrapcheck

linters-settings:
  exhaustive:
    check:
      - switch
      - map
